no exfat update

diff --git a/offline_update b/offline_update
--- a/offline_update
+++ b/offline_update
@@ -52,9 +52,9 @@ case "$confirm" in
 esac
 
 echo
-echo "==> Checking camera DATA mount"
-if ! ssh "$REMOTE" 'mountpoint -q /data && test -d /data/configs'; then
-    die "Remote /data is not mounted or /data/configs is missing on ${REMOTE}."
+echo "==> Checking camera data directory"
+if ! ssh "$REMOTE" 'test -d /home/pi/data/configs'; then
+    die "Remote /home/pi/data/configs is missing on ${REMOTE}."
 fi
 
 echo
